version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_ERLANG_COOKIE: "secret-cookie"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres:
    build:
      context: .
      dockerfile: deployment/postgres/Dockerfile
    container_name: postgres
    platform: linux/arm64
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  franchise-service:
    build:
      context: ./franchise
      dockerfile: deployment/Dockerfile
    container_name: franchise-service
    platform: linux/arm64
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_HOST: postgres
      SPRING_DATASOURCE_PORT: 5432
      SPRING_DATASOURCE_DATABASE: main_nequi_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_DATASOURCE_SCHEMA: franchise_db
      ADAPTER_RABBITMQ_HOST: rabbitmq
      ADAPTER_RABBITMQ_PORT: "5672"

  branch-service:
    build:
      context: ./branch
      dockerfile: deployment/Dockerfile
    container_name: branch-service
    platform: linux/arm64
    ports:
      - "8081:8081"
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_HOST: postgres
      SPRING_DATASOURCE_PORT: 5432
      SPRING_DATASOURCE_DATABASE: main_nequi_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_DATASOURCE_SCHEMA: branch_db
      ADAPTER_RABBITMQ_HOST: rabbitmq
      ADAPTER_RABBITMQ_PORT: "5672"

  product-service:
    build:
      context: ./product
      dockerfile: deployment/Dockerfile
    container_name: product-service
    platform: linux/arm64
    ports:
      - "8083:8083"
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_HOST: postgres
      SPRING_DATASOURCE_PORT: 5432
      SPRING_DATASOURCE_DATABASE: main_nequi_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_DATASOURCE_SCHEMA: product_db
      ADAPTER_RABBITMQ_HOST: rabbitmq
      ADAPTER_RABBITMQ_PORT: "5672"

volumes:
  rabbitmq-data:
  postgres-data:
